### ISSUE TITLE
Could not download the omnidirectional dataset

### ISSUE THREAD

**Issue by flying-gwx** [COATZ/OmniFlowNet#1]
cannot download the dataset in http://www.i3s.unice.fr/~allibert/data/OMNIFLOWNET_DATASET.zip, the webpage can open but it is shut  down immediately.

**Comment by COATZ** [comment]
Hi,
I've checked the link and have no issue using it with Firefox or Safari. 
Could you check your browser settings or test it on another one?
Best regards.

**Comment by flying-gwx** [comment]
the problem is solved when I use https instand of http. 
https://www.i3s.unice.fr/~allibert/data/OMNIFLOWNET_DATASET.zip works.

**Comment by flying-gwx** [comment]
Hello,
I downloaded the dataset with Chrome and it did not work. Howerver, the problem is solved when I use https instand of http. 
https://www.i3s.unice.fr/~allibert/data/OMNIFLOWNET_DATASET.zip works. 
I will close the issue. Thank you for your reply!

Wenxuan Gao
Shanghai Jiao Tong University

发件人: COATZ
发送时间: 2021年11月15日 17:47
收件人: COATZ/OmniFlowNet
抄送: Weason; Author
主题: Re: [COATZ/OmniFlowNet] Could not download the omnidirectionaldataset (Issue #1)

Hi,
I've checked the link and have no issue using it with Firefox or Safari.
Could you check your browser settings or test it on another one?
Best regards.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by COATZ** [comment]
Thanks a lot for your feedback. I updated the README with the https url.
If you have any questions concerning the dataset you can directly contact me at [artizzu@i3s.unice.fr](artizzu@i3s.unice.fr).
Cheers.
